#!/bin/sh
bazel run //:bazeldnf -- fetch \
    --repofile rpm/repo.yaml
bazel run //:bazeldnf -- rpmtree \
    --workspace rpms.bzl \
    --buildfile rpm/BUILD.bazel \
    --repofile rpm/repo.yaml \
    --name cryptsetup-devel \
    cryptsetup-devel
bazel run //rpm:ldd
